kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-cluster
nodes:
- role: control-plane
  extraMounts:
  - containerPath: '/usr/local/share/ca-certificates/extra/'
    hostPath: 'registry/certs/'
# add worker nodes by duplicating and uncommenting the following
#- role: worker
#  extraMounts:
#  - containerPath: '/usr/local/share/ca-certificates/extra/'
#    hostPath: 'registry/certs/'
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."$HOSTNAME:443"]
    endpoint = ["https://kind-registry:443"]
